export const books = [
  // Old Testament (39 books)
  { name: "Genesis", abbreviation: "Gen", testament: "OT" },
  { name: "Exodus", abbreviation: "Exo", testament: "OT" },
  { name: "Leviticus", abbreviation: "Lev", testament: "OT" },
  { name: "Numbers", abbreviation: "Num", testament: "OT" },
  { name: "Deuteronomy", abbreviation: "Deut", testament: "OT" },
  { name: "Joshua", abbreviation: "Josh", testament: "OT" },
  { name: "Judges", abbreviation: "Judg", testament: "OT" },
  { name: "Ruth", abbreviation: "Ruth", testament: "OT" },
  { name: "1 Samuel", abbreviation: "1Sam", testament: "OT" },
  { name: "2 Samuel", abbreviation: "2Sam", testament: "OT" },
  { name: "1 Kings", abbreviation: "1Kgs", testament: "OT" },
  { name: "2 Kings", abbreviation: "2Kgs", testament: "OT" },
  { name: "1 Chronicles", abbreviation: "1Chr", testament: "OT" },
  { name: "2 Chronicles", abbreviation: "2Chr", testament: "OT" },
  { name: "Ezra", abbreviation: "Ezra", testament: "OT" },
  { name: "Nehemiah", abbreviation: "Neh", testament: "OT" },
  { name: "Esther", abbreviation: "Esth", testament: "OT" },
  { name: "Job", abbreviation: "Job", testament: "OT" },
  { name: "Psalms", abbreviation: "Ps", testament: "OT" },
  { name: "Proverbs", abbreviation: "Prov", testament: "OT" },
  { name: "Ecclesiastes", abbreviation: "Eccl", testament: "OT" },
  { name: "Song of Solomon", abbreviation: "Song", testament: "OT" },
  { name: "Isaiah", abbreviation: "Isa", testament: "OT" },
  { name: "Jeremiah", abbreviation: "Jer", testament: "OT" },
  { name: "Lamentations", abbreviation: "Lam", testament: "OT" },
  { name: "Ezekiel", abbreviation: "Ezek", testament: "OT" },
  { name: "Daniel", abbreviation: "Dan", testament: "OT" },
  { name: "Hosea", abbreviation: "Hos", testament: "OT" },
  { name: "Joel", abbreviation: "Joel", testament: "OT" },
  { name: "Amos", abbreviation: "Amos", testament: "OT" },
  { name: "Obadiah", abbreviation: "Obad", testament: "OT" },
  { name: "Jonah", abbreviation: "Jonah", testament: "OT" },
  { name: "Micah", abbreviation: "Mic", testament: "OT" },
  { name: "Nahum", abbreviation: "Nah", testament: "OT" },
  { name: "Habakkuk", abbreviation: "Hab", testament: "OT" },
  { name: "Zephaniah", abbreviation: "Zeph", testament: "OT" },
  { name: "Haggai", abbreviation: "Hag", testament: "OT" },
  { name: "Zechariah", abbreviation: "Zech", testament: "OT" },
  { name: "Malachi", abbreviation: "Mal", testament: "OT" },

  // New Testament (27 books)
  { name: "Matthew", abbreviation: "Matt", testament: "NT" },
  { name: "Mark", abbreviation: "Mark", testament: "NT" },
  { name: "Luke", abbreviation: "Luke", testament: "NT" },
  { name: "John", abbreviation: "John", testament: "NT" },
  { name: "Acts", abbreviation: "Acts", testament: "NT" },
  { name: "Romans", abbreviation: "Rom", testament: "NT" },
  { name: "1 Corinthians", abbreviation: "1Cor", testament: "NT" },
  { name: "2 Corinthians", abbreviation: "2Cor", testament: "NT" },
  { name: "Galatians", abbreviation: "Gal", testament: "NT" },
  { name: "Ephesians", abbreviation: "Eph", testament: "NT" },
  { name: "Philippians", abbreviation: "Phil", testament: "NT" },
  { name: "Colossians", abbreviation: "Col", testament: "NT" },
  { name: "1 Thessalonians", abbreviation: "1Thess", testament: "NT" },
  { name: "2 Thessalonians", abbreviation: "2Thess", testament: "NT" },
  { name: "1 Timothy", abbreviation: "1Tim", testament: "NT" },
  { name: "2 Timothy", abbreviation: "2Tim", testament: "NT" },
  { name: "Titus", abbreviation: "Titus", testament: "NT" },
  { name: "Philemon", abbreviation: "Phlm", testament: "NT" },
  { name: "Hebrews", abbreviation: "Heb", testament: "NT" },
  { name: "James", abbreviation: "Jas", testament: "NT" },
  { name: "1 Peter", abbreviation: "1Pet", testament: "NT" },
  { name: "2 Peter", abbreviation: "2Pet", testament: "NT" },
  { name: "1 John", abbreviation: "1John", testament: "NT" },
  { name: "2 John", abbreviation: "2John", testament: "NT" },
  { name: "3 John", abbreviation: "3John", testament: "NT" },
  { name: "Jude", abbreviation: "Jude", testament: "NT" },
  { name: "Revelation", abbreviation: "Rev", testament: "NT" },
];
