-- CreateTable
CREATE TABLE "ProjectedVerse" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "verseId" INTEGER NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ProjectedVerse_verseId_fkey" FOREIGN KEY ("verseId") REFERENCES "Verse" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
